permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: isaac
  email: isaacdjxdjx@gmail.com
  link: http://isaacdjx.github.io
  github: http://github.com/isaacdjx

# 站点信息
title: Isaac's Blog 
description: Isaac's Blog 
url: http://isaacdjx.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/pic/avatar/avatar.jpg
favicon: /assets/pic/avatar/avatar.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: suyan-zh